#!/usr/bin/env bash
# Regenerates src/sf-symbols.js — Apple's SF Symbols, rendered by macOS itself
# at 4x into tintable masks, one JS module shared by the Mac and iPhone apps.
#
# ⚠️ WHY MASKS AND NOT SVG. Apple ships the symbols as vector assets inside a
# private bundle, not as a font with public glyph names; the only public way to
# get one out is NSImage(systemSymbolName:), and drawing that into a PDF
# rasterises. A 4x alpha PNG used as a CSS mask, tinted with currentColor, is
# pixel-exact at every size the apps use (17–28pt) on 2x and 3x screens.
#
# ⚠️ LICENSE. SF Symbols may be used only in apps for Apple platforms. The Mac
# app and the iPhone app qualify; the website and the Chrome extension do NOT
# and must keep their own icons. Never import this module from them.
#
#   scripts/sf-symbols.sh          # rebuild from the list below
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=src/sf-symbols.js
TMP=$(mktemp -d)
swiftc -O scripts/sf/render.swift -o "$TMP/render" 2>/dev/null
# name:weight — regular unless the HIG uses another for that role
SYMBOLS="gearshape:regular chevron.left:semibold chevron.right:semibold chevron.down:semibold ellipsis.circle:regular arrow.down.circle:regular checkmark:semibold photo:regular arrow.up:semibold stop.fill:regular square.and.pencil:regular info.circle:regular trash:regular xmark:semibold archivebox:regular magnifyingglass:regular camera:regular mic:regular plus:semibold ellipsis:regular"
{
  echo "// GENERATED by scripts/sf-symbols.sh — do not edit. Apple SF Symbols, rendered"
  echo "// by macOS at 4x as alpha masks. Apple-platform apps only (see the script)."
  echo "export const SF_SYMBOLS = {"
  for pair in $SYMBOLS; do
    name=${pair%%:*}; weight=${pair##*:}
    mkdir -p "$TMP/$weight"
    line=$("$TMP/render" "$TMP/$weight" "$weight" 22 "$name")
    pt=$(echo "$line" | sed -E 's/.* ([0-9.]+)x([0-9.]+)pt.*/\1 \2/')
    w=${pt% *}; h=${pt#* }
    b64=$(base64 -i "$TMP/$weight/$name.png" | tr -d '\n')
    echo "  '$name': { w: $w, h: $h, weight: '$weight', src: 'data:image/png;base64,$b64' },"
  done
  echo "}"
} > "$OUT"
rm -rf "$TMP"
echo "$OUT: $(grep -c "src: 'data" "$OUT") symbols, $(du -h "$OUT" | cut -f1)"
